modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/0xJoeMama/VoidMagic/issues"

[[mods]]
modId = "voidmagic"
version = "1.0.0"
displayName = "Void Magic"
displayURL = "https://github.com/0xJoeMama/VoidMagic"
logoFile = "voidmagic_icon.png"
authors = "KaloyanKYS, DigitalPear, 0xJoeMama"
description = '''
A magic mod that allows you to delve deep into the darkest corners of your world.
Be ready for you will encounter frightening magic, creatures and worlds.
'''

[[dependencies.voidmagic]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.voidmagic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

# Adding curios as a mandatory dependency.
[[dependencies.voidmagic]]
modId = "curios"
mandatory = true
versionRange = "[1.16.5-4.0.5.0,)"
ordering = "NONE"
side = "BOTH"

# Add JEI as a possible dependency.
[[dependencies.voidmagic]]
modId = "jei"
mandatory = false
versionRange = "[7.6.1.75,)"
ordering = "NONE"
side = "CLIENT"